/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.superdelnorte.ui;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import mx.itson.superdelnorte.entities.Articulo;
import mx.itson.superdelnorte.entities.Recibo;

/**
 *
 * @author pedrizquierdo
 */
public class SuperDelNorteForm extends javax.swing.JFrame {

    /**
     * Creates new form SuperDelNorteForm
     */
    public SuperDelNorteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSucursal = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        labelGerente = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        labelNombreCliente = new javax.swing.JLabel();
        labelRfc = new javax.swing.JLabel();
        labelDireccion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableArticulos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        labelFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelSucursal.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        labelSucursal.setText("Sucursal: ");

        labelTelefono.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        labelTelefono.setText("Teléfono: ");

        labelGerente.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        labelGerente.setText("Gerente: ");

        labelCliente.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        labelCliente.setText("Cliente");

        labelNombreCliente.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        labelNombreCliente.setText("Nombre: ");

        labelRfc.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        labelRfc.setText("RFC: ");

        labelDireccion.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        labelDireccion.setText("Dirección: ");
        labelDireccion.setToolTipText("");

        tableArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio", "IVA", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tableArticulos);

        jButton1.setText("Seleccionar archivo...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        labelFecha.setText("00/00/00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDireccion)
                    .addComponent(labelRfc)
                    .addComponent(labelNombreCliente)
                    .addComponent(labelCliente)
                    .addComponent(labelGerente)
                    .addComponent(labelTelefono)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSucursal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(336, 336, 336))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSucursal)
                    .addComponent(labelFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTelefono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelGerente)
                .addGap(18, 18, 18)
                .addComponent(labelCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelRfc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDireccion)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try{
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
            
            if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
                File file = fileChooser.getSelectedFile();
                
                byte  fileBytes[] = Files.readAllBytes(file.toPath());
                String contenido = new String(fileBytes, StandardCharsets.UTF_8);
                
            Recibo recibo = new Recibo().deserializar(contenido);  
            
            labelSucursal.setText("Sucursal: " + recibo.getSucursal().getNombre());
            labelTelefono.setText("Teléfono: " + recibo.getSucursal().getTelefono());
            labelGerente.setText("Gerente: " + recibo.getSucursal().getGerente());
            labelNombreCliente.setText("Cliente: "+ recibo.getCliente().getNombre());
            labelRfc.setText("RFC: "+ recibo.getCliente().getRfc());
            labelDireccion.setText("Dirección: " + recibo.getCliente().getDireccion());


            labelTelefono.setText("Teléfono: " + recibo.getSucursal().getTelefono());
            labelGerente.setText("Gerente: " + recibo.getSucursal().getGerente());
            labelNombreCliente.setText("Cliente: "+ recibo.getCliente().getNombre());
            labelRfc.setText("RFC: "+ recibo.getCliente().getRfc());


            
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy", new Locale("ES","mx"));
            
            labelFecha.setText(dateFormat.format(recibo.getFecha()));
            
            
            DefaultTableModel model = (DefaultTableModel) tableArticulos.getModel();
            model.setRowCount(0);
            
            for(Articulo a : recibo.getArticulos()) {
                model.addRow(new Object[]{
                    a.getCodigo(),
                    a.getPrecio(),
                    a.getTasaIva(),
                    
                });
            }
         
            
            }
            
        }catch (Exception ex) {
            System.err.println(ex.getMessage());
        }
        
        
    


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuperDelNorteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuperDelNorteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuperDelNorteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuperDelNorteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuperDelNorteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelDireccion;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelGerente;
    private javax.swing.JLabel labelNombreCliente;
    private javax.swing.JLabel labelRfc;
    private javax.swing.JLabel labelSucursal;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JTable tableArticulos;
    // End of variables declaration//GEN-END:variables
}

